USE [master]
GO

/****** Object:  Database [lykosdb]    Script Date: 16.06.2017 16:44:33 ******/
CREATE DATABASE [lykosdb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'lykosdb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\lykosdb.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'lykosdb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\lykosdb_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [lykosdb] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [lykosdb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [lykosdb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [lykosdb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [lykosdb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [lykosdb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [lykosdb] SET ARITHABORT OFF 
GO

ALTER DATABASE [lykosdb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [lykosdb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [lykosdb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [lykosdb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [lykosdb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [lykosdb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [lykosdb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [lykosdb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [lykosdb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [lykosdb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [lykosdb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [lykosdb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [lykosdb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [lykosdb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [lykosdb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [lykosdb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [lykosdb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [lykosdb] SET RECOVERY FULL 
GO

ALTER DATABASE [lykosdb] SET  MULTI_USER 
GO

ALTER DATABASE [lykosdb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [lykosdb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [lykosdb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [lykosdb] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [lykosdb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [lykosdb] SET  READ_WRITE 
GO

