USE [master]
GO

/****** Object:  Database [lykos]    Script Date: 22.06.2017 16:40:37 ******/
CREATE DATABASE [lykos]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'lykos', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.VIKTOR\MSSQL\DATA\lykos.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'lykos_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.VIKTOR\MSSQL\DATA\lykos_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [lykos] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [lykos].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [lykos] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [lykos] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [lykos] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [lykos] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [lykos] SET ARITHABORT OFF 
GO

ALTER DATABASE [lykos] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [lykos] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [lykos] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [lykos] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [lykos] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [lykos] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [lykos] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [lykos] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [lykos] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [lykos] SET  DISABLE_BROKER 
GO

ALTER DATABASE [lykos] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [lykos] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [lykos] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [lykos] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [lykos] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [lykos] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [lykos] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [lykos] SET RECOVERY FULL 
GO

ALTER DATABASE [lykos] SET  MULTI_USER 
GO

ALTER DATABASE [lykos] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [lykos] SET DB_CHAINING OFF 
GO

ALTER DATABASE [lykos] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [lykos] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [lykos] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [lykos] SET  READ_WRITE 
GO

